CC:=			cc
CFLAGS:=		-std=gnu99 -I/usr/local/include
LIBS:=			-L/usr/local/lib -lsqlite3 -lutil -lm -ldl -lssl -lcrypto -lssh -lmosquitto -lrt
EXTRAOBJS:=     strlcpy/strlcpy.o strlcpy/strlcat.o

LIBTOOLIZE:=    libtoolize

DEPS_LUA_TARGET:=	linux
DEPS_JAMLIB_MAKEFILE:=	Makefile.linux

MAGIEDIT_ANSI_PATH:= ""
MAGIEDIT_DRAFT_PATH:= ""

include GNUmakefile.common
