CC:=			gcc-9
CFLAGS:=		-std=gnu99 -I/usr/local/include -I/usr/include/gmp
LIBS:=			-L/usr/lib -L/usr/local/lib -lsqlite3 -lm -ldl -lssl -lcrypto -lssh -lmosquitto -lnsl -lsocket -lssp
EXTRAOBJS:=     os/sunos.o

LIBTOOLIZE:=    libtoolize

DEPS_LUA_TARGET:=	solaris
DEPS_JAMLIB_MAKEFILE:=	Makefile.sunos

MAGIEDIT_ANSI_PATH:= ""
MAGIEDIT_DRAFT_PATH:= ""

include GNUmakefile.common
