CC:=			egcc
CFLAGS:=		-std=gnu99 -I/usr/local/include
LIBS:=			-L/usr/local/lib -lsqlite3 -lutil -lm -lssl -lcrypto -lssh -liconv -lmosquitto

LIBTOOLIZE:=    libtoolize

DEPS_LUA_TARGET:=	bsd
DEPS_JAMLIB_MAKEFILE:=	Makefile.linux

MAGIEDIT_ANSI_PATH:= ""
MAGIEDIT_DRAFT_PATH:= ""

include GNUmakefile.common
